import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>

    <style jsx>
    {`
    h2{
      font-size: 32px
    }
    h3{
      font-size: 20px
    }
    `}
    </style>

      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs ,Hunting coder blog,next blog" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
        <h1 className={styles.title}><span className='myspan'>&lt;Hunting Coder/&gt;</span></h1>

        {/*<Image className={styles.myImg} src='/hutningcoder.avif' width={158} height={118} alt='home image'></Image>*/}

        <img className={styles.myImg} src="/hutningcoder.avif" width={158} height={118} alt="home image"/>

        <p className={styles.description}>A blog for Coders</p>

        <div className={styles.blogs}>
          <div><h2>Popular Blogs</h2></div>
          <div className={styles.blogItem}>
            <h3>How to Learn javascript in 2022</h3>
            <p>JavaScript is language designed to write logic for the web development</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to Learn javascript in 2022</h3>
            <p>JavaScript is language designed to write logic for the web development</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to Learn javascript in 2022</h3>
            <p>JavaScript is language designed to write logic for the web development</p>
          </div>
        </div>

      </main>


    </>
  )
}
